### ISSUE TITLE
Hardcoded versions in view.py

### ISSUE THREAD

**Issue by Toporin** [Tech-Aware/Satochip-utils#1]
The versions shown in the about screen are hardcoded:

self.version = self.create_label("Satochip-utils version: 0.4.1")
self.pysatochip_version = self.create_label("Pysatochip version: 0.12.6")

For pysatochip_version, the version of library can be found in pysatochip/version.py

For self.version (better call it self.app_version), the version should be hardcoded as a constant in the beginning of the file or in its own file. 

A CHANGELOG should also be defined in root folder (see e.g. https://github.com/Toporin/Satodime-Android/blob/master/CHANGELOG.md)

**Comment by Tech-Aware** [comment]
fixed
