### ISSUE TITLE
Card version parsing is incorrect

### ISSUE THREAD

**Issue by Toporin** [Tech-Aware/Satochip-utils#2]
In "about" screen.

The card version is of the form vX.Y-Z.W
with protocol_major_version.protocol_minor_version-applet_major_version.applet_minor_version

**Comment by Tech-Aware** [comment]
> In "about" screen.
> 
> The card version is of the form vX.Y-Z.W with protocol_major_version.protocol_minor_version-applet_major_version.applet_minor_version

I was to think about the possibility to add the card_version directly into the status dictionnary ? What about it ?
